### ISSUE TITLE
APIService 구조 수정

### ISSUE THREAD

**Issue by eogus4658** [AppCenter-Snaptime/snaptime-iOS#22]
## 📜 설명
> 현재 APIService 내에서 json 디코딩까지 다 하고 있어서 클래스가 복잡해졌는데, APIService에서는 alamofire를 이용한 통신 작업만 하게끔 역할을 나눠주는 건 어때? 여기서 json 디코딩은 따로 관련 모듈을 만들어도 되고, 아니면 apiservice 호출하는 쪽에서 그냥 클로저 내부에 작성하는 게 좋은 것 같아! 어떻게 생각해?

## ✔️ 작업 상세 내용

<img width="1440" alt="image" src="https://github.com/AppCenter-Snaptime/snaptime-iOS/assets/58897339/edfbd169-c4c4-4715-94cf-6d9f39654ffe">

<img width="1440" alt="image" src="https://github.com/AppCenter-Snaptime/snaptime-iOS/assets/58897339/32964b49-1ca9-4d39-aba0-99dbd7691562">

**Comment by blwxnhan** [comment]
json 디코딩 관련해서 모듈을 새로 만드는 것 좋은 것 같아! 호출하는 쪽 클로져 내부에서 하면 거기가 엄청 복잡해질것 같다....
